---

- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Upgrading all packages (CentOS)
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install a few more packages
  package:
    name: "{{item}}"
    state: installed
  with_items:
   - vim
   - htop

- name: Install the `unattended-upgrades` package
  package:
    name: unattended-upgrades
    state: installed
  when: ansible_os_family == "Debian"

- name: Copy the `20auto-upgrades` configuration file
  copy:
    src: ../templates/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"
